name: CI

on:
  push:
    branches: [main]
  release:
    types: [created]
  pull_request:
  schedule:
    - cron: '35 2 * * *' # run nightly at 2:35 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build and Verify
        run: ./mvnw -B clean verify
            -Dstyle.color=always
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Publish Nightly Update Site
        if: github.event_name != 'release' && github.ref == 'refs/heads/main' && github.repository_owner == 'kit-sdq'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: kit-sdq/updatesite
          destination_dir: nightly/metamodels/demo
          publish_dir: releng/edu.kit.ipd.sdq.metamodels.demo.updatesite/target/repository
          publish_branch: master
      - name: Publish Release Update Site
        if: github.event_name == 'release' && github.repository_owner == 'kit-sdq'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: kit-sdq/updatesite
          destination_dir: release/metamodels/demo/${{ github.event.release.tag_name }}
          publish_dir: releng/edu.kit.ipd.sdq.metamodels.demo.updatesite/target/repository
          publish_branch: master
          

